export const CATALOG_LIST_REQUEST = 'CATALOG_LIST_REQUEST';
export const CATALOG_LIST_SUCCESS = 'CATALOG_LIST_SUCCESS';
export const CATALOG_LIST_FAIL = 'CATALOG_LIST_FAIL';

export const CATALOG_DETAILS_REQUEST = 'CATALOG_DETAILS_REQUEST';
export const CATALOG_DETAILS_SUCCESS = 'CATALOG_DETAILS_SUCCESS';
export const CATALOG_DETAILS_FAIL = 'CATALOG_DETAILS_FAIL';

export const CATALOG_DELETE_REQUEST = 'CATALOG_DELETE_REQUEST';
export const CATALOG_DELETE_SUCCESS = 'CATALOG_DELETE_SUCCESS';
export const CATALOG_DELETE_FAIL = 'CATALOG_DELETE_FAIL';

export const CATALOG_CREATE_REQUEST = 'CATALOG_CREATE_REQUEST';
export const CATALOG_CREATE_SUCCESS = 'CATALOG_CREATE_SUCCESS';
export const CATALOG_CREATE_FAIL = 'CATALOG_CREATE_FAIL';
export const CATALOG_CREATE_RESET = 'CATALOG_CREATE_RESET';

export const CATALOG_UPDATE_REQUEST = 'CATALOG_UPDATE_REQUEST';
export const CATALOG_UPDATE_SUCCESS = 'CATALOG_UPDATE_SUCCESS';
export const CATALOG_UPDATE_FAIL = 'CATALOG_UPDATE_FAIL';
export const CATALOG_UPDATE_RESET = 'CATALOG_UPDATE_RESET';

export const CATALOG_CREATE_REVIEW_REQUEST = 'CATALOG_CREATE_REVIEW_REQUEST';
export const CATALOG_CREATE_REVIEW_SUCCESS = 'CATALOG_CREATE_REVIEW_SUCCESS';
export const CATALOG_CREATE_REVIEW_FAIL = 'CATALOG_CREATE_REVIEW_FAIL';
export const CATALOG_CREATE_REVIEW_RESET = 'CATALOG_CREATE_REVIEW_RESET';

export const CATALOG_TOP_REQUEST = 'CATALOG_TOP_REQUEST';
export const CATALOG_TOP_SUCCESS = 'CATALOG_TOP_SUCCESS';
export const CATALOG_TOP_FAIL = 'CATALOG_TOP_FAIL';
