@hostname = 10.47.10.24

@port = 5000

@host = {{hostname}}:{{port}}

@protocol = http://

@url = {{protocol}}{{host}}

@contentType = application/json

@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNTllYTU0OWRjNGZiZTAwN2QzMjRhNiIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYzMzI4Mjc2Mn0.OS68g8RHc_GxJ520WkeBKSmwiy7JSfx6NRrEZXeY7Jo

### Get Token
POST {{url}}/api/auth
Content-Type: {{contentType}}

{
  "email": "sohan@ndub.edu.bd",
  "password": "1234afaf56"
}