@hostname = localhost

@port = 5000

@host = {{hostname}}:{{port}}

@protocol = http://

@url = {{protocol}}{{host}}

@contentType = application/json

### Get Token
POST {{url}}/api/auth
Content-Type: {{contentType}}

{
  "email": "sohan@ndub.edu.bd",
  "password": "rickyonkjaura"
}