@hostname = localhost

@port = 5000

@host = {{hostname}}:{{port}}

@protocol = http://

@url = {{protocol}}{{host}}

@contentType = application/json

@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNTkyZDZiNzRhODZmMzQyNmVmYzQ0MyIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYzMzIzNDI4M30.DCqQrpe02415-pWCiidfsGve746Vt4S1SnHJjE-A17g


GET {{url}}/api/entries
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoicmlja3kiLCJpc0FkbWluIjp0cnVlfQ.3SAosAkfh49GtFA1t30-7ImmoIKzAgbtxYsthn-R8wM


###
GET {{url}}/api/entries?pageNumber=1&pageSize=50&sortBy=entryNumber&order=asc&entryNumber=
x-auth-token: {{adminToken}}



###

POST {{url}}/api/entries
Content-Type: {{contentType}}
x-auth-token: {{adminToken}}

{
  "entryNumber": 1,
  "title": "Hellow",
  "author": "Ricky Rozario"
}