@hostname = localhost

@port = 5000

@host = {{hostname}}:{{port}}

@protocol = http://

@url = {{protocol}}{{host}}

@contentType = application/json

@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNTllYTU0OWRjNGZiZTAwN2QzMjRhNiIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYzMzI4Mjc2Mn0.OS68g8RHc_GxJ520WkeBKSmwiy7JSfx6NRrEZXeY7Jo


GET {{url}}/api/entries
x-auth-token: {{adminToken}}


###
GET {{url}}/api/entries?pageNumber=1&pageSize=50&sortBy=date&order=desc
x-auth-token: {{adminToken}}

###

POST {{url}}/api/entries
Content-Type: {{contentType}}
x-auth-token: {{adminToken}}

{
  "entryNumber": 1001,
  "title": "Hellow",
  "author": "Ricky Rozario"
}