@hostname = localhost

@port = 5000

@host = {{hostname}}:{{port}}

@protocol = http://

@url = {{protocol}}{{host}}

@contentType = application/json



### Add an user
### Access  Public
POST {{url}}/api/users
Content-Type: {{contentType}}

{
  "username": "sohan",
  "email": "sohan@ndub.edu.bd",
  "password": "rickyonkjaura",
  "isAdmin": true
}


